name: Build and Deploy

on:
    push:
        branches:
            - electron
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: windows-latest

        permissions:
            contents: write

        steps:
            - name: Checkout electron branch
              uses: actions/checkout@v4
              with:
                  ref: electron

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/Iron'

            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm install

            - name: Build the application
              run: npm run build

            - name: Create backup
              run: |
                  mkdir -p ../backup
                  cp dist/Pixlr-1.0.0-Setup.exe ../backup/

            - name: Checkout main branch
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Create public directory
              run: mkdir -p public

            - name: Restore files
              run: |
                  rm -rf public/Pixlr-1.0.0-Setup.exe
                  mv ../backup/cp dist/Pixlr-1.0.0-Setup.exe public/

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Commit and push changes
              run: |
                  git add dist public
                  git commit -m "Update dist and public directories with latest build"
                  git push origin main
