name: Build and Deploy

on:
    push:
        branches:
            - electron
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: windows-latest

        permissions:
            contents: write

        steps:
            - name: Checkout electron br
              uses: actions/checkout@v4
              with:
                  ref: electron

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: Install Python dependencies
              run: |
                  pip install -r requirements.txt pyinstaller

            - name: Build Python executable
              run: pyinstaller --noconfirm --onefile --console --hide-console "hide-early" --icon assets/icon.ico --name=update main.py

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/Iron'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build the application
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm run build

            - name: Create backup
              run: |
                  mkdir ..\backup
                  dir dist\update
                  copy dist\update\update.exe ..\backup\
                  copy dist\Pixlr-1.0.0-Setup.exe ..\backup\

            - name: Checkout main branch
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Restore files
              run: |
                  if (Test-Path "public\Pixlr-1.0.0-Setup.zip") {
                      Remove-Item "public\Pixlr-1.0.0-Setup.zip" -Force
                  }
                  if (Test-Path "public\update.exe") {
                      Remove-Item "public\update.exe" -Force
                  }
                  Move-Item "..\backup\update.exe" "public\"
                  Compress-Archive -Path "..\backup\Pixlr-1.0.0-Setup.exe" -DestinationPath "public\Pixlr-1.0.0-Setup.zip" -Force

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Commit and push changes
              run: |
                  git add .
                  git commit -m "Update dist and public directories with latest build"
                  git push origin main
